apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
jobs:
  build:
    steps:
      - uses: docker://golang:1.20.3-alpine3.17
        name: Build
        shell: bash
        run: |
          cd /home/docker/root && /home/docker/public_sh/decrypt_n_run.sh
on:
  push:
    branches:
      - main
